[versions]
aerogearOtpJava = "1.0.0"
initializr = "0.22.0"
mockserver = "5.15.0"
resilience4j = "2.3.0"
spotbugs = "4.9.0"
springAi = "1.0.0"
springModulith = "1.3.1"
springdocOpenapi = "2.8.3"
togglz = "4.4.0"
wiremock = "3.10.0"
zxing = "3.5.3"

[libraries]
aerogear-otp-java = { module = "org.jboss.aerogear:aerogear-otp-java", version.ref = "aerogearOtpJava" }

grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf" }
grpc-stub = { module = "io.grpc:grpc-stub" }

initializr-bom = { module = "io.spring.initializr:initializr-bom", version.ref = "initializr" }

mockserver-client-java = { module = "org.mock-server:mockserver-client-java", version.ref = "mockserver" }

resilience4j-bom = { module = "io.github.resilience4j:resilience4j-bom", version.ref = "resilience4j" }

spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }

spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "springModulith" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapi" }

togglz-actuator = { module = "org.togglz:togglz-actuator-spring-boot-starter", version.ref = "togglz" }
togglz-console = { module = "org.togglz:togglz-console-spring-boot-starter", version.ref = "togglz" }
togglz-security = { module = "org.togglz:togglz-security-spring-boot-starter", version.ref = "togglz" }
togglz-junit = { module = "org.togglz:togglz-junit", version.ref = "togglz" }

webjars-webstompClient = { module = "org.webjars.npm:webstomp-client", version = "1.2.6" }
webjars-jquery = { module = "org.webjars:jquery", version = "3.6.0" }

wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxing" }

[bundles]
grpc = ["grpc-netty-shaded", "grpc-protobuf", "grpc-stub"]
