[versions]
aerogearOtpJava = "1.0.0"
mockserver = "5.15.0"
openrewrite = "6.19.0"
resilience4j = "2.3.0"
springAi = "1.1.0"
springGrpc = "1.0.0-RC1"
springModulith = "2.0.0"
springdocOpenapi = "3.0.0"
wiremock = "3.13.1"
wiremockIntegrations = "4.0.6"
zxing = "3.5.3"

[libraries]
aerogear-otp-java = { module = "org.jboss.aerogear:aerogear-otp-java", version.ref = "aerogearOtpJava" }

grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf" }
grpc-stub = { module = "io.grpc:grpc-stub" }

mockserver-client-java = { module = "org.mock-server:mockserver-client-java", version.ref = "mockserver" }

openrewrite-spring = { module = "org.openrewrite.recipe:rewrite-spring", version.ref = "openrewrite" }

resilience4j-bom = { module = "io.github.resilience4j:resilience4j-bom", version.ref = "resilience4j" }

spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }

spring-grpc-dependencies = { module = "org.springframework.grpc:spring-grpc-dependencies", version.ref = "springGrpc" }

spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "springModulith" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapi" }

webjars-webstompClient = { module = "org.webjars.npm:webstomp-client", version = "1.2.6" }
webjars-jquery = { module = "org.webjars:jquery", version = "3.6.0" }

wiremock-standalone = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }

wiremock-integrations-springBoot = { module = "org.wiremock.integrations:wiremock-spring-boot", version.ref = "wiremockIntegrations" }

zxing-javase = { module = "com.google.zxing:javase", version.ref = "zxing" }

[bundles]
grpc = ["grpc-netty-shaded", "grpc-protobuf", "grpc-stub"]
